=begin
#AUM Immo

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'

# Unit tests for SwisseldexAumImmo::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwisseldexAumImmo::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(SwisseldexAumImmo::DefaultApi)
    end
  end

  # unit tests for upload
  # Upload
  # Post a new change of contract message for automatic processing to VNB.
  # @param [Hash] opts the optional parameters
  # @option opts [UploadMessage] :body Structure and property-names are adapted from eCH-0112 (https://www.ech.ch/de/standards/52687).
  # @option opts [BOOLEAN] :test_delivery Processes message but does not forward it to recognized VNB (for testing)
  # @option opts [String] :carbon_copy_email If VNB is consuming the message via Email, this address is taken as CC (mainly intended for testing). Adress is only considered if the mail-server supports TLS (you can check this with e.g. https://www.checktls.com/TestReceiver). Value of this parameter is not validated and it won&#x27;t cause a negative impact on the processing of the message.
  # @return [UploadResponse]
  describe 'upload test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
