=begin
#AUM Immo

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwisseldexAumImmo::UploadMessageExtensionSourceSystemReferences
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UploadMessageExtensionSourceSystemReferences' do
  before do
    # run before each test
    @instance = SwisseldexAumImmo::UploadMessageExtensionSourceSystemReferences.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UploadMessageExtensionSourceSystemReferences' do
    it 'should create an instance of UploadMessageExtensionSourceSystemReferences' do
      expect(@instance).to be_instance_of(SwisseldexAumImmo::UploadMessageExtensionSourceSystemReferences)
    end
  end
  describe 'test attribute "contract"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "building"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "dwelling"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
