=begin
#AUM Immo

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwisseldexAumImmo::UploadMessageExtensionIdxObjectInfo
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UploadMessageExtensionIdxObjectInfo' do
  before do
    # run before each test
    @instance = SwisseldexAumImmo::UploadMessageExtensionIdxObjectInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UploadMessageExtensionIdxObjectInfo' do
    it 'should create an instance of UploadMessageExtensionIdxObjectInfo' do
      expect(@instance).to be_instance_of(SwisseldexAumImmo::UploadMessageExtensionIdxObjectInfo)
    end
  end
  describe 'test attribute "idx_object_category"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "idx_object_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
