=begin
#AUM Immo

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.3.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'SwisseldexAumImmo/api_client'
require 'SwisseldexAumImmo/api_error'
require 'SwisseldexAumImmo/version'
require 'SwisseldexAumImmo/configuration'

# Models
require 'SwisseldexAumImmo/models/upload_message'
require 'SwisseldexAumImmo/models/upload_message_building'
require 'SwisseldexAumImmo/models/upload_message_contract'
require 'SwisseldexAumImmo/models/upload_message_contractor'
require 'SwisseldexAumImmo/models/upload_message_contractor_postal_address'
require 'SwisseldexAumImmo/models/upload_message_dwelling'
require 'SwisseldexAumImmo/models/upload_message_extension'
require 'SwisseldexAumImmo/models/upload_message_extension_additional_person_data'
require 'SwisseldexAumImmo/models/upload_message_extension_additional_persons'
require 'SwisseldexAumImmo/models/upload_message_extension_idx_object_info'
require 'SwisseldexAumImmo/models/upload_message_extension_previous_person'
require 'SwisseldexAumImmo/models/upload_message_extension_source_application'
require 'SwisseldexAumImmo/models/upload_message_extension_source_system_references'
require 'SwisseldexAumImmo/models/upload_message_goes_to'
require 'SwisseldexAumImmo/models/upload_message_person'
require 'SwisseldexAumImmo/models/upload_response'
require 'SwisseldexAumImmo/models/upload_response_data_corrections'
require 'SwisseldexAumImmo/models/upload_response_data_corrections_building_address'
require 'SwisseldexAumImmo/models/upload_response_provider_details'

# APIs
require 'SwisseldexAumImmo/api/default_api'

module SwisseldexAumImmo
  class << self
    # Customize default settings for the SDK using block.
    #   SwisseldexAumImmo.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
